[
  inputs: ["mix.exs", "{config,lib,test}/**/*.{ex,exs}"],
  line_length: 120,
  locals_without_parens: [
    configure: 1,
    pipeline: 2,
    plug: 1,
    plug: 2,
    incoming: 2,
    pipe_through: 1,
    subscribe: 2,
    subscribe: 3,
    outgoing: 1,
    publish: 1,
    publish: 2,
    exchange: 1,
    exchange: 2,
    queue: 1,
    queue: 2,
    assert_message_published: 1,
    assert_message_published: 2,
    refute_message_published: 1,
    refute_message_published: 2,
    assert_message_publish: 1,
    assert_message_publish: 2,
    refute_message_publish: 1,
    refute_message_publish: 2
  ],
  export: [
    locals_without_parens: [
      configure: 1,
      pipeline: 2,
      plug: 1,
      plug: 2,
      incoming: 2,
      pipe_through: 1,
      subscribe: 2,
      subscribe: 3,
      outgoing: 1,
      publish: 1,
      publish: 2,
      exchange: 1,
      exchange: 2,
      queue: 1,
      queue: 2,
      assert_message_published: 1,
      assert_message_published: 2,
      refute_message_published: 1,
      refute_message_published: 2,
      assert_message_publish: 1,
      assert_message_publish: 2,
      refute_message_publish: 1,
      refute_message_publish: 2
    ]
  ]
]
